# Generated by Django 4.2.3 on 2023-08-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='size',
        ),
    ]
