# Generated by Django 4.2.3 on 2023-08-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_mobile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
