# Generated by Django 4.2.3 on 2023-08-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
