# Generated by Django 4.2.3 on 2023-07-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Cancelled', 'Cancelled')], default='Pending', max_length=150),
        ),
    ]
