# Generated by Django 4.2.3 on 2023-07-26 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_size_product_sizes'),
        ('checkout', '0004_remove_orderitem_variation_orderitem_selected_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='selected_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Return', 'Return'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=150),
        ),
    ]
