# Generated by Django 4.2.3 on 2023-08-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Return', 'Return'), ('Processing', 'Processing'), ('Shipped', 'Shipped')], default='Pending', max_length=150),
        ),
    ]
