# Generated by Django 4.2.3 on 2023-08-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Return', 'Return'), ('Processing', 'Processing'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
