# Generated by Django 4.2.3 on 2023-08-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0024_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Processing', 'Processing'), ('Pending', 'Pending'), ('Return', 'Return')], default='Pending', max_length=150),
        ),
    ]
