# Generated by Django 4.2.3 on 2023-08-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0029_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Return', 'Return'), ('Delivered', 'Delivered'), ('Processing', 'Processing')], default='Pending', max_length=150),
        ),
    ]
