# Generated by Django 4.2.3 on 2023-08-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0031_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Return', 'Return'), ('Delivered', 'Delivered')], default='Pending', max_length=150),
        ),
    ]
