# Generated by Django 4.2.3 on 2023-08-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0038_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Return', 'Return'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled')], default='Pending', max_length=150),
        ),
    ]
