# Generated by Django 4.2.3 on 2023-08-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_delete_guestuser_cart_session_id_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
    ]
